### PR TITLE
Build windows wheels

### LINKED ISSUE #15: windows support
Hi @martinellimarco 

I wanted to experiment if it's complicated to provide `indexed_zstd` as windows wheels, and put together a working example. As a disclaimer: my C and windows knowledge is enough to get stuff done for me, but very far from knowing anything about best practices, and/or why some things are done the way they are. 

see:
- https://github.com/ap--/indexed_zstd/tree/windows
- https://github.com/ap--/libzstd-seek/tree/windows

It's just a hack for now, since it assumes that you install and build it in a conda environment.
But it might be a good starting point if there's interest in providing `indexed_zstd` for windows too.

Here's running the test script on windows:

```powershell
(iz) C:\Users\andreas\Development\indexed_zstd\test>python test.py
Block offset completed?:  False
{0: 0, 17: 4, 32: 6, 49: 10, 78: 26}
Block offset completed?:  True
Test reading letters from A to Z
ABCDEFGHIJKLMNOPQRSTUVWXYZ
Tell is 26:  26
Compressed tell is 78:  78
Seeking back to 15
Tell is 15?:  15
Compressed tell is 49:  49
Filesize is 26?  26
Compressed tell is 49:  49
Reading a byte after EOF
Compressed tell is 78:  78
Test reading again, letters from P to Z
QRSTUVWXYZ
Testing set_block_offsets
Block offset completed?:  False
{0: 0, 17: 4, 32: 6, 49: 10, 78: 26}
Block offset completed?:  True
```

To build on windows:
```powershell
git clone --recurse-submodules -b windows https://github.com/ap--/indexed_zstd.git
conda create -n iz python=3.11 zstd conda-build
conda activate iz
pip install ./indexed_zstd
```

I guess if someone is interested and feels more at home in the windows c-extension python world, it should be easy for them to clean this up. (We could then provide windows pkgs in conda-forge too.)

Cheers,
Andreas 😃

### PR DESCRIPTION
**Pull request by ap--**
Closes #15 

Add windows wheels.

Still needs to:
- [x] fix test on python 3.11 (fails due to change in dll load behaviour in py38+ https://docs.python.org/3/whatsnew/3.8.html#changes-in-the-python-api)
- [x] do the delocate/auditwheel equivalent on cibuildwheel for windows? https://github.com/adang1345/delvewheel

### CODE REVIEW

**Comment by ap--** [comment]
Hi Marco,
I managed to fix the issues :smiley:

**Comment by martinellimarco** [comment]
Looks good to me :)

I've compiled and tested it locally and so far it is working as expected.

Unless you have anything else to change I will first merge your pull request on [libzstd-seek ](https://github.com/martinellimarco/libzstd-seek/pull/5)

Then we can change the submodule in this pull request to refer to mainstream libzstd-seek and merge it.

Sounds good to you?

**Comment by martinellimarco** [comment]
Hi @ap-- ,
I've merged libzstd-seek, update the submodule to upstream then I will merge this and publish a new version.

Thanks a lot for your contribution, it was really appreciated :)

**Comment by ap--** [comment]
@martinellimarco I cleaned it up a bit and think this is good to go now!

**Comment by martinellimarco** [comment]
@ap-- version 1.6.0 is published :) Thanks again!

**Pull request merged**
